services:
  db:
    image: postgres:alpine
    env_file:
      - ./be/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    env_file:
      - ./be/.env
    ports:
        - 5672:5672
        - 15672:15672

volumes:
  pgdata: